version: '3.9'

services:

  database:
    image: 'postgres:14-alpine'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - 5432:5432
